working_directory: &working_directory
  ~/project

defaults: &defaults
  docker:
    - image: circleci/node:8.12.0-stretch-browsers
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  dependencies-{{ checksum "package.json" }}

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: *repo_cache_key
  lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_repo
      - run: npm run lint:javascript
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_repo
      - run: npm run test

workflows:
  version: 2
  gates:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare

