export const fatalities = [
  {
    "Age": 13,
    "Case": "19-0400694",
    "DOB": "12/05/2005",
    "Date": "02/09/2019",
    "Ethnicity": "Black",
    "Fatal crashes this year": "7",
    "First Name": "Zion",
    "Gender": "male",
    "Last Name": "Mouton",
    "Link": "http://austintexas.gov/news/traffic-fatality-7-4",
    "Location": "6000 block of Springdale Road",
    "Notes": "The preliminary investigation shows that the driver of a 1997, red BMW was traveling northbound in the 6000 block of Springdale Road and lost control. The vehicle skidded sideways before flipping and striking a utility pole. The passenger in the vehicle, Messiah Zion Mouton, was pronounced deceased at the scene.",
    "Time": "12:48 p.m."
  },
  {
    "Age": 32,
    "Case": "19-0370320",
    "DOB": "02/18/1986",
    "Date": "02/06/2019",
    "Ethnicity": "White",
    "Fatal crashes this year": "6",
    "First Name": "James",
    "Gender": "male",
    "Last Name": "Ralston",
    "Link": "http://austintexas.gov/news/traffic-fatality-6-6",
    "Location": "1000 block of W. Oltorf Street",
    "Notes": "The preliminary investigation shows that the driver of a gray, 2008 Mini Cooper was travelling westbound in the 1000 block of W. Oltorf Street when she lost control and slid into the eastbound path of a gray, 2018 Honda motorcycle. The motorcycle, driven by Trevor Ralston, struck the right side of the Mini Cooper. Trevor Ralston was pronounced deceased on scene. The driver of the Mini Cooper remained at the crash location and was cited for failure to control speed.",
    "Time": "7:02 a.m."
  },
  {
    "Age": 21,
    "Case": "19-0320079",
    "DOB": "10/23/1997",
    "Date": "02/01/2019",
    "Ethnicity": "White",
    "Fatal crashes this year": "5",
    "First Name": "Mark",
    "Gender": "male",
    "Last Name": "Sands",
    "Link": "http://austintexas.gov/news/traffic-fatality-5-7",
    "Location": "500 block N. IH 35 service road southbound",
    "Notes": "The preliminary investigation shows that a 2006 silver Volkswagen Jetta operated by an Uber driver was traveling southbound in the right lane of N. IH-35 southbound on the service road. The Jetta changed lanes to enter the ramp of southbound IH 35 when it encountered a Lime scooter. The pedestrian on the scooter was traveling the wrong way, northbound in the southbound left lane of the IH-35 service road. The pedestrian was transported to Dell Seton Medical Center at the University of Texas. He was pronounced deceased at 2:30 p.m. on Saturday, Feb. 2, 2019. The Uber driver remained on scene and is cooperating as this investigation continues. The toxicology results in this case are still pending.",
    "Time": "12:52 a.m."
  },
  {
    "Age": 58,
    "Case": "19-0260086",
    "DOB": "12/31/1960",
    "Date": "01/26/2019",
    "Ethnicity": "White",
    "Fatal crashes this year": "4",
    "First Name": "Laura",
    "Gender": "female",
    "Last Name": "Wray",
    "Link": "http://austintexas.gov/news/traffic-fatality-4-6",
    "Location": "6900 block N. IH-35 SB",
    "Time": "1:02 a.m.",
    "Vehicle": "2014 Ford F-150 (black)"
  },
  {
    "Age": 15,
    "Case": "19-0081623",
    "DOB": "02/18/2003",
    "Date": "01/08/2019",
    "Ethnicity": "Hispanic",
    "Fatal crashes this year": "3",
    "First Name": "Jesus",
    "Gender": "male",
    "Last Name": "Servantez",
    "Link": "http://austintexas.gov/news/traffic-fatality-3-4",
    "Location": "3600 block of South Capital of Texas Highway SB",
    "Notes": "The preliminary investigation shows that the driver of a silver, 2018 KIA was traveling in the center lane of the 3600 block of South Capital of Texas Highway SB when the car collided with Jesus Servantez, a pedestrian in the roadway. The driver remained at the scene and told investigators that he did not see Servantez prior to the crash. Jesus Servantez was transported to Saint David\u2019s South Austin Medical Center where he succumbed to his injuries on January 21, 2019. No charges are expected to be filed. APD is investigating this case. Anyone with information regarding this case should call APD\u2019s Vehicular Homicide Unit Detectives at (512) 974-3761. You can also submit tips by downloading APD\u2019s mobile app, Austin PD, for free on iPhone and Android. This is Austin\u2019s third fatal traffic crash of 2018, resulting in three fatalities this year. At this time in 2018, there were two fatal traffic crashes and three traffic fatalities. These statements are based on the initial assessment of the fatal crash and investigation is still pending. Fatality information may change.",
    "Time": "9:37 p.m."
  },
  {
    "Age": 31,
    "Case": "19-0150158",
    "DOB": "07/09/1987",
    "Date": "01/15/2019",
    "Ethnicity": "White",
    "Fatal crashes this year": "1",
    "First Name": "Hilburn",
    "Gender": "male",
    "Last Name": "Sell",
    "Link": "http://austintexas.gov/news/traffic-fatality-1-4",
    "Location": "10500 block of N IH 35 SB",
    "Notes": "The preliminary investigation shows that a 2000 Peterbilt semi truck was travelling southbound in the center lane on IH 35 when it struck pedestrian David Sell. The driver stopped as soon as it was possible to do so and remained on scene. He reported not seeing the pedestrian prior to impact given that it was still dark at the time of the crash. Sell was pronounced deceased at the scene at 6:24 a.m. No charges are expected to be filed. APD is investigating this case. Anyone with information regarding this case should call APD\u2019s Vehicular Homicide Unit Detectives at (512) 974-3761. You can also submit tips by downloading APD\u2019s mobile app, Austin PD, for free on iPhone and Android. This is Austin\u2019s first fatal traffic crash of 2018, resulting in one fatality this year. At this time in 2018, there was one fatal traffic crash and two traffic fatalities. These statements are based on the initial assessment of the fatal crash and investigation is still pending. Fatality information may change.",
    "Time": "6:20 a.m."
  },
  {
    "Age": 58,
    "Case": "19-0161105",
    "DOB": "02/15/1960",
    "Date": "01/16/2019",
    "Ethnicity": "White",
    "Fatal crashes this year": "2",
    "First Name": "Ann",
    "Gender": "female",
    "Last Name": "Bottenfield-Seago",
    "Link": "http://austintexas.gov/news/traffic-fatality-2-3",
    "Location": "West William Cannon Drive and Ridge Oak Road",
    "Notes": "The preliminary investigation shows that the grey, 2003 Volkwagen Jetta being driven by Ann Bottenfield-Seago failed to yield at a stop sign while attempting to turn westbound on to West William Cannon Drive from Ridge Oak Road. The Jetta collided with a black, 2017 Chevrolet truck that was eastbound in the inside lane of West William Cannon Drive. Bottenfield-Seago was pronounced deceased at the scene. The passenger in the Jetta and the driver of the truck were both transported to a local hospital with non-life threatening injuries. No charges are expected to be filed. APD is investigating this case. Anyone with information regarding this case should call APD\u2019s Vehicular Homicide Unit Detectives at (512) 974-3761. You can also submit tips by downloading APD\u2019s mobile app, Austin PD, for free on iPhone and Android. This is Austin\u2019s second fatal traffic crash of 2018, resulting in two fatalities this year. At this time in 2018, there were two fatal traffic crashes and three traffic fatalities. These statements are based on the initial assessment of the fatal crash and investigation is still pending. Fatality information may change.",
    "Time": "3:42 p.m."
  },
  {
    "Age": 19,
    "Case": "19-0581824",
    "DOB": "01/20/2000",
    "Date": "02/27/2019",
    "Ethnicity": "Hispanic",
    "Fatal crashes this year": "10",
    "First Name": "Ni\u00f1o",
    "Gender": "male",
    "Last Name": "Esparza",
    "Link": "http://austintexas.gov/news/traffic-fatality-10-4",
    "Location": "East 7th Street and Springdale Road",
    "Notes": "The preliminary investigation shows a white, 2000 Lexus RX300 was traveling eastbound on East 7th Street when the driver ran a red light and struck a grey, 2004 Volkswagen Golf moving northbound on Springdale Road. The force of the impact caused both the Lexus and Volkswagen to also strike a white, 2019 Jeep Cherokee that was stopped at the red light. The driver of the Volkswagen Golf, Javier Emanuel Nin\u0303o Esparza, was pronounced deceased at the scene. The driver of the Lexus, Duane Harris, 29, was transported to a local hospital for treatment following the crash as were two other occupants from the vehicle. Harris has been charged with intoxication manslaughter.",
    "Time": "10:25 p.m."
  },
  {
    "Age": 64,
    "Case": "19-0521894",
    "DOB": "10/10/1954",
    "Date": "02/21/2019",
    "Ethnicity": "Hispanic",
    "Fatal crashes this year": "9",
    "First Name": "\u201cRudy\u201d",
    "Gender": "male",
    "Last Name": "Tamez",
    "Link": "http://austintexas.gov/news/traffic-fatality-9-4",
    "Location": "7300 block of E. Riverside Dr.",
    "Notes": "The preliminary investigation shows a silver 2017 Jeep Patriot was traveling eastbound in the 7300 block of E. Riverside Dr. A pedestrian, Rosbel Tamez, was crossing Riverside near Uphill St. when he was struck by the Jeep. Mr. Tamez was transported to St. David\u2019s South Austin Hospital where he died a short time later. ",
    "Time": "11:56 p.m."
  },
  {
    "Age": 37,
    "Case": "19-0521569",
    "DOB": "04/15/1981",
    "Date": "02/21/2019",
    "Ethnicity": "White",
    "Fatal crashes this year": "8",
    "First Name": "Blair",
    "Gender": "female",
    "Last Name": "Dismukes",
    "Link": "http://austintexas.gov/news/traffic-fatality-8-4",
    "Location": "8100 block of N. Lamar Blvd.",
    "Notes": "The preliminary investigation shows that two pedestrians were crossing mid-block in the 8100 block of N. Lamar Blvd. when both were struck by an unknown vehicle. One pedestrian had minor injuries and the other was pronounced deceased at the scene. The vehicle that hit them fled and has not been yet identified. ",
    "Time": "8:30 p.m."
  },
  {
    "Age": 13,
    "Case": "19-0400694",
    "DOB": "12/05/2005",
    "Date": "02/09/2019",
    "Ethnicity": "Black",
    "Fatal crashes this year": "7",
    "First Name": "Zion",
    "Gender": "male",
    "Last Name": "Mouton",
    "Link": "http://austintexas.gov/news/traffic-fatality-7-4",
    "Location": "6000 block of Springdale Road",
    "Notes": "The preliminary investigation shows that the driver of a 1997, red BMW was traveling northbound in the 6000 block of Springdale Road and lost control. The vehicle skidded sideways before flipping and striking a utility pole. The passenger in the vehicle, Messiah Zion Mouton, was pronounced deceased at the scene.",
    "Time": "12:48 p.m."
  }
]
